name: CI/CD Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./build

    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Bash for GitHub Actions
      uses: jcblw/bash@1.0.0
      args: ["mkdir build"]
    - name: cmake
      run: cmake ..
    - name: make
      run: make    
    - name: make install
      run: sudo make install